name: Run bouf
description: Generates signed OBS install files and updater files
inputs:
  gcpWorkloadIdentityProvider:
    description: GCP Identity Provider Pool ID
    required: true
  gcpServiceAccountName:
    description: Google service account name
    required: true
  gcpManifestSigningKeyName:
    description: Name of the manifest signing key in GCP KMS
    required: false
  version:
    description: Version string (e.g., 30.0.0-rc1)
    required: true
  channel:
    description: Update channel
    required: false
    default: 'stable'

runs:
  using: composite
  steps:
    - name: Get Token
      shell: pwsh
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        . ${env:GITHUB_ACTION_PATH}\Ensure-Location.ps1
        . ${env:GITHUB_ACTION_PATH}\Invoke-External.ps1
        Ensure-Location output
        Invoke-External curl -i -H "Authorization: bearer ${env:ACTIONS_ID_TOKEN_REQUEST_TOKEN}" "${env:ACTIONS_ID_TOKEN_REQUEST_URL}&audience=test" -o jwt.json
