name: Run bouf
description: Generates signed OBS install files and updater files
inputs:
  updaterPrivateKey:
    description: Private key for signing update manifest
    required: true
  driveServiceAccount:
    description: base64-encoded Google service account file for syncing old builds for delta generation
    required: true
  kmsServiceAccount:
    description: base64-encoded Google service account file for code signing
    required: true
  kmsServiceAccountName:
    description: Google service account name
    required: true
  version:
    description: Version string (e.g. 30.0.0-rc1)
    required: true
  channel:
    description: Update channel
    required: false
    default: 'stable'

runs:
  using: composite
  steps:
    - name: Checkout bouf repo
      uses: actions/checkout@v4
      with:
        repository: 'obsproject/bouf'
        path: 'bouf-repo'

    - name: Extract build
      shell: bash
      run: |
        cd build
        unzip -q *.zip
        rm *.zip

    - name: Setup rclone
      shell: bash
      run: |
        mkdir rclone && cd rclone
        curl -O -L https://downloads.rclone.org/v1.64.2/rclone-v1.64.2-windows-amd64.zip
        # todo hash check
        unzip rclone-v1.64.2-windows-amd64.zip
        echo '${{ github.workspace }}\rclone\rclone-v1.64.2-windows-amd64' >> $GITHUB_PATH

    - name: Setup bouf
      shell: bash
      run: |
        mkdir bouf && cd bouf
        curl -O -L https://r2.rodney.io/bouf-build-windows-latest.zip
        # todo hash check
        unzip bouf-build-windows-latest.zip
        echo "${{ github.workspace }}\bouf" >> $GITHUB_PATH

    - name: Download Google CNG Provider
      shell: bash
      run: |
        mkdir gcng && cd gcng
        curl -O -L https://github.com/GoogleCloudPlatform/kms-integrations/releases/download/cng-v0.9/kmscng-0.9-windows-amd64.zip
        unzip kmscng-0.9-windows-amd64.zip
        openssl dgst -sha384 -verify ../repo/build-aux/bouf/cng-release-signing-key.pem -signature kmscng-0.9-windows-amd64/kmscng.msi.sig kmscng-0.9-windows-amd64/kmscng.msi

    - name: Setup Google CNG Provider
      shell: cmd
      run: |
        msiexec /i gcng\kmscng-0.9-windows-amd64\kmscng.msi /qn /norestart

    - name: Download Google Cloud CLI
      shell: bash
      run: |
        mkdir gcloud-cli && cd gcloud-cli
        curl -O -L https://dl.google.com/dl/cloudsdk/channels/rapid/GoogleCloudSDKInstaller.exe

    - name: Install Google Cloud CLI
      shell: cmd
      run: |
        gcloud-cli\GoogleCloudSDKInstaller.exe /S

    - name: Restore service accounts
      shell: bash
      env:
        DRIVE_BASE64: ${{ inputs.driveServiceAccount }}
        KMS_BASE64: ${{ inputs.kmsServiceAccount }}
      run: |
        echo $DRIVE_BASE64 | base64 --decode > sa-drive.json
        echo $KMS_BASE64 | base64 --decode > sa-kms.json

    - name: Download old builds
      shell: pwsh
      run: |
        rclone -v copy --drive-shared-with-me --drive-service-account-file ${{ github.workspace }}/sa-drive.json :drive:old_builds old_builds

    - name: Log into gcloud
      shell: pwsh
      env:
        ACCOUNT_NAME: ${{ inputs.kmsServiceAccountName }}
      run: |
        gcloud auth activate-service-account ${ACCOUNT_NAME} --key-file=${{ github.workspace }}/sa-kms.json

    - name: Run bouf
      shell: pwsh
      env:
        UPDATER_PRIVATE_KEY: ${{ inputs.updaterPrivateKey }}
      run: |
        bouf --config repo/build-aux/bouf/config.toml --version ${{ inputs.version }} -i build -p old_builds -o output --clear-output
