name: Run bouf Patch Generation
description: Generates OBS updater manifest and patches
inputs:
  gcsAccessKeyId:
    description: GCS S3 Access Key ID
    required: true
  gcsAccessKeySecret:
    description: GCS S3 Access Key Secret
    required: true
  workflowSecret:
    description: GitHub API token to use for API calls
    required: true
  tagName:
    description: GitHub Release tag
    required: true
  channel:
    description: Update channel
    required: false
    default: 'stable'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        path: "repo"
        fetch-depth: 0

    - name: Prepare Release Notes
      shell: pwsh
      run: |
        # Release notes are just the tag body on Windows
        Set-Location repo
        git tag
        git tag -l --format='%(contents:body)' ${{ inputs.tagName }}
        git tag -l --format='%(contents:body)' ${{ inputs.tagName }} > "${{ github.workspace }}/notes.rst"

    - name: Upload Outputs
      uses: actions/upload-artifact@v4
      with:
        name: windows-updater-files
        compression-level: 9
        path: ${{ github.workspace }}/notes.rst
