name: Generate Documentation

on:
  push:
    paths-ignore:
      - "cmake/**"
  pull_request:
    paths:
      - "docs/sphinx/**"
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Environment
        id: setup
        run: |
          echo "commitHash=$(git describe --exact-match --tags 2> /dev/null || git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Bump Version Number
        shell: bash
        if: github.event_name == 'push'
        run: |
          VERTEST="\#define\sLIBOBS_API_\w+_VER\s([0-9]{1,2})"
          VER=""
          MAJOR=""
          while IFS= read -r l
          do
              if [[ $l =~ $VERTEST ]]; then
                  if [[ $VER = '' ]]; then MAJOR="${BASH_REMATCH[1]}"; else VER+="."; fi
                  VER+="${BASH_REMATCH[1]}"
              fi
          done < "libobs/obs-config.h"

          SVER="version = '([0-9\.]+)'"
          RVER="version = '69.4.20'"
          SREL="release = '([0-9\.]+)'"
          RREL="release = '69'"
          SCOPY="copyright = '([A-Za-z0-9, ]+)'"
          RCOPY="copyright = '1970-$(date +"%Y"), Hugh Bailey'"
          sed -i -E -e "s/${SVER}/${RVER}/g" -e "s/${SREL}/${RREL}/g" -e "s/${SCOPY}/${RCOPY}/g" docs/sphinx/conf.py
      - uses: totaldebug/sphinx-publish-action@1.2.0
        with:
          sphinx_src: 'docs/sphinx'
          build_only: True
          target_branch: 'master'
          target_path: '../home/_build'
          pre_build_commands: 'pip install -Iv sphinx==5.1.1'
      - uses: actions/upload-artifact@v3
        with:
          name: 'OBS Studio Docs ${{ steps.setup.outputs.commitHash }}'
          path: |
            ${{ runner.temp }}/_github_home/_build
            !${{ runner.temp }}/_github_home/_build/.doctrees
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ runner.temp }}/_github_home/_build

  deploy:
    runs-on: ubuntu-latest
    needs: docs
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: true
    steps:
      - name: Publish
        id: deployment
        uses: actions/deploy-pages@v1
