name: 'BUILD'

on:
  push:

env:
  CACHE_REVISION: '006'
  CEF_BUILD_VERSION_MAC: '5060'
  CEF_HASH_MAC_X86_64: '88b950aa0bfc001061c35e7f1f3fefba856a6afb35e38b2b7b42ddd8dd239182'
  CEF_HASH_MAC_ARM64: '98679b92eea6ea9959ac5aa54f46ca60681d8a86c768c35f496dbdd409bf0642'
  CEF_BUILD_VERSION_LINUX: '5060'
  CEF_BUILD_VERSION_WIN: '5060'
  QT_VERSION_MAC: '6.4.1'
  QT_HASH_MAC_X86_64: 'c5ed7bc9f6e802910ec539066bcf0a8d64100fafce568071f264c88c22c5859b'
  QT_HASH_MAC_ARM64: '1ce472fd1e28f947456b72b1d7ab929d6e93cb774c2928e22eca9bb751b12ccf'
  QT_HASH_MAC_UNIVERSAL: '873f7c9c9f7fcee740a79c075b32a505c932c816d928807fa16f3439c610fbfd'
  QT_VERSION_WIN: '6.3.1'
  DEPS_VERSION_MAC: '2022-11-21'
  DEPS_HASH_MAC_X86_64: 'ed0a145e88496f8975da14a07939dbe5633e60510aada34509a4aef64a66e438'
  DEPS_HASH_MAC_ARM64: 'f397dc524e5ee7f85684f0b9661c45957446e28d166fcd6dfacf895c9d4d2521'
  DEPS_VERSION_WIN: '2023-01-06'
  VLC_VERSION_MAC: '3.0.8'
  VLC_HASH_MAC: 'e0149ef4a20a19b9ecd87309c2d27787ee3f47dfd47c6639644bc1f6fd95bdf6'
  VLC_VERSION_WIN: '3.0.0-git'
  TWITCH_CLIENTID: ${{ secrets.TWITCH_CLIENT_ID }}
  TWITCH_HASH: ${{ secrets.TWITCH_HASH }}
  RESTREAM_CLIENTID: ${{ secrets.RESTREAM_CLIENTID }}
  RESTREAM_HASH: ${{ secrets.RESTREAM_HASH }}
  YOUTUBE_CLIENTID: ${{ secrets.YOUTUBE_CLIENTID }}
  YOUTUBE_CLIENTID_HASH: ${{ secrets.YOUTUBE_CLIENTID_HASH }}
  YOUTUBE_SECRET: ${{ secrets.YOUTUBE_SECRET }}
  YOUTUBE_SECRET_HASH: ${{ secrets.YOUTUBE_SECRET_HASH }}

jobs:
  config:
    name: '01 - Configure Build Jobs'
    runs-on: [ubuntu-22.04]
    env:
      HAVE_SPARKLE_KEY: ${{ secrets.SPARKLE_PRIVATE_KEY != '' }}
    outputs:
      create_artifacts: ${{ steps.config.outputs.create_artifacts }}
      cache_date: ${{ steps.config.outputs.cache_date }}
      run_sparkle: ${{ steps.config.outputs.run_sparkle }}
    steps:
      - name: 'Configure Build Jobs'
        id: config
        run: |
          if [[ "${{ github.event_name == 'pull_request' }}" == "true" ]]; then
            echo "create_artifacts=${{ contains(github.event.pull_request.labels.*.name, 'Seeking Testers') }}" >> $GITHUB_OUTPUT
          else
            echo 'create_artifacts=true' >> $GITHUB_OUTPUT
          fi
          echo "cache_date=$(date +"%Y-%m-%d")" >> $GITHUB_OUTPUT

  macos_sparkle:
    name: '04 - macOS Sparkle Updates'
    runs-on: [macos-12]
    needs: [config]
    if: needs.config.outputs.run_sparkle == 'true'
    strategy:
      matrix:
        arch: ['x86_64', 'arm64']
    env:
      SPARKLE_VERSION: '2.3.2'
      SPARKLE_HASH: '2b3fe6918ca20a83729aad34f8f693a678b714a17d33b5f13ca2d25edfa7eed3'
    defaults:
      run:
        shell: bash
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          path: 'repo'
          ref: ${{ github.ref }}

      - name: 'Download artifact'
        run: |
          mkdir artifacts
          cd artifacts
          wget "https://r2.rodney.io/sparkle/obs-studio-29.0.0-beta1-f6ed7c43b-macos-${{ matrix.arch }}.dmg"
          wget "https://r2.rodney.io/sparkle/obs-studio-29.0.0-beta1-4df2b83f2-macos-${{ matrix.arch }}.dmg"

      - name: 'Install Python requirements'
        run: pip3 install requests xmltodict

      - name: 'Install Brew requirements'
        run: brew install coreutils pandoc

      - name: 'Setup Sparkle'
        run: |
          curl -L "https://github.com/sparkle-project/Sparkle/releases/download/${{ env.SPARKLE_VERSION }}/Sparkle-${{ env.SPARKLE_VERSION }}.tar.xz" -o Sparkle.tar.xz

          if [[ '${{ env.SPARKLE_HASH }}' != "$(sha256sum Sparkle.tar.xz | cut -d " " -f 1)" ]]; then
              echo "Sparkle download hash does not match!"
              exit 1
          fi

          mkdir sparkle && cd sparkle
          tar -xf ../Sparkle.tar.xz

      - name: 'Setup folder structure'
        run: |
          mkdir builds
          mkdir -p output/appcasts
          mkdir -p output/deltas/${{ matrix.arch }}

      - name: 'Determine branch and tag'
        id: branch
        run: |
          pushd repo
          
          GIT_TAG="$(git describe --tags --abbrev=0)"
          if [[ ${GIT_TAG} == *'beta'* || ${GIT_TAG} == *'rc'* ]]; then
            echo "branch=beta" >> $GITHUB_OUTPUT
            echo "deltas=0" >> $GITHUB_OUTPUT
          else
            echo "branch=stable" >> $GITHUB_OUTPUT
            echo "deltas=1" >> $GITHUB_OUTPUT
          fi
          # Write tag description to file
          git tag -l --format='%(contents)' ${GIT_TAG} >> ../notes.rst

      - name: 'Download existing Appcast and builds'
        env:
          BRANCH: ${{ steps.branch.outputs.branch }}
          DELTAS: ${{ steps.branch.outputs.deltas }}
          ARCH: ${{ matrix.arch }}
        run: python3 repo/CI/macos/appcast_download.py

      - name: 'Prepare release notes'
        run: |
          # Insert underline at line 2 to turn first line into heading
          sed -i '' '2i\'$'\n''###################################################' notes.rst
          pandoc -f rst -t html notes.rst -o output/appcasts/notes_${{ steps.branch.outputs.branch }}.html

      - name: 'Setup Sparkle key'
        run: echo -n "${{ secrets.SPARKLE_PRIVATE_KEY }}" >> eddsa_private.key

      - name: 'Generate Appcast'
        run: |
          mv artifacts/*.dmg builds/
          ./sparkle/bin/generate_appcast \
              --verbose \
              --ed-key-file ./eddsa_private.key \
              --download-url-prefix "https://cdn-fastly.obsproject.com/downloads/" \
              --full-release-notes-url "https://obsproject.com/osx_update/notes_${{ steps.branch.outputs.branch }}.html" \
              --maximum-versions 0 \
              --maximum-deltas ${{ steps.branch.outputs.deltas }} \
              --channel "${{ steps.branch.outputs.branch }}" builds/
          # Move deltas, if any
          if compgen -G "builds/*.delta" > /dev/null; then
            mv builds/*.delta output/deltas/${{ matrix.arch }}
          fi
          # Move appcasts
          mv builds/*.xml output/appcasts/

      - name: 'Create 1.x Appcast'
        run: python3 repo/CI/macos/appcast_convert.py

      - name: 'Upload Appcast and Deltas'
        uses: actions/upload-artifact@v3
        with:
          name: 'macos-sparkle-updates'
          path: '${{ github.workspace }}/output'
